# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 06:07
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suporrt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '技术支持',
                'verbose_name': '技术支持',
            },
        ),
    ]
