# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20170916_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suport',
            new_name='Support',
        ),
    ]
