# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20170916_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'verbose_name': '产品中心', 'verbose_name_plural': '产品中心'},
        ),
    ]
