# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seconditem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='thirditem',
            name='system',
        ),
        migrations.AddField(
            model_name='seconditem',
            name='frist_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.FristItem', verbose_name='一级标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thirditem',
            name='second_system',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.SecondItem', verbose_name='二级标题'),
            preserve_default=False,
        ),
    ]
