# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 16:10
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20170916_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirditem',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='内容'),
        ),
    ]
