# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 13:36
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20170916_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '科技服务主页',
                'verbose_name': '科技服务主页',
            },
        ),
    ]
