# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_serviceindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fristitem',
            options={'verbose_name': '科研服务一级分类', 'verbose_name_plural': '科研服务一级分类'},
        ),
        migrations.AlterModelOptions(
            name='seconditem',
            options={'verbose_name': '科研服务二级目录', 'verbose_name_plural': '科研服务二级目录'},
        ),
        migrations.AlterModelOptions(
            name='serviceindex',
            options={'verbose_name': '科研服务主页', 'verbose_name_plural': '科研服务主页'},
        ),
        migrations.AlterModelOptions(
            name='thirditem',
            options={'verbose_name': '科研服务内容目录', 'verbose_name_plural': '科研服务内容目录'},
        ),
    ]
