# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='carousel/%Y/%m/%d', verbose_name='图片')),
                ('link', models.URLField(null=True, verbose_name='链接地址')),
                ('display', models.IntegerField(default=1, null=True, verbose_name='显示')),
            ],
            options={
                'ordering': ['display', '-id'],
            },
        ),
    ]
