# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 02:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170915_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', ckeditor.fields.RichTextField(verbose_name='公司介绍')),
            ],
            options={
                'verbose_name': '公司介绍',
                'ordering': ['-id'],
                'verbose_name_plural': '公司介绍',
            },
        ),
    ]
