# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='module/%Y/%m/%d', verbose_name='图片')),
                ('link', models.URLField(blank=True, null=True, verbose_name='链接地址')),
            ],
            options={
                'verbose_name': '首页三图片（只能填三个）',
                'verbose_name_plural': '首页三图片（只能填三个）',
            },
        ),
    ]
