# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 08:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_moduleimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-id'], 'verbose_name': '关于奥美德诺', 'verbose_name_plural': '关于奥美德诺'},
        ),
        migrations.AlterField(
            model_name='company',
            name='introduction',
            field=ckeditor.fields.RichTextField(verbose_name='关于奥美德诺'),
        ),
    ]
