# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170922_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '关于奥美德诺', 'verbose_name_plural': '关于奥美德诺'},
        ),
    ]
