# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170922_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='关键词')),
            ],
            options={
                'verbose_name': '网站关键词',
                'verbose_name_plural': '网站关键词',
            },
        ),
    ]
