# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date', '-id'], 'verbose_name': '新闻动态', 'verbose_name_plural': '新闻动态'},
        ),
    ]
