# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': '基础技术服务', 'verbose_name_plural': '基础技术服务'},
        ),
    ]
