# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='职位')),
                ('work_place', models.CharField(max_length=128, verbose_name='工作地点')),
                ('duty', models.TextField(verbose_name='岗位职责')),
                ('request', models.TextField(verbose_name='岗位要求')),
            ],
            options={
                'verbose_name': '招贤纳士',
                'verbose_name_plural': '招贤纳士',
            },
        ),
    ]
